### ISSUE TITLE
Local Problem

### ISSUE THREAD

**Issue by reboutte** [lionep/amixer-parser#1]
Hello, 
I'm french, and my debian's local to..

aplay -l say

***** Liste des Périphériques Matériels PLAYBACK ****
carte 0: Intel [HDA Intel], périphérique 0: ALC269 Analog [ALC269 Analog]
  Sous-périphériques: 1/1

I replace card with carte near line 120 in parser.js and parser work...

Befor that,  amixer-parser don't parse.

**Comment by lionep** [comment]
Hi, thanks for this report.

It's now fixed in v1.0.4, I add support for FR and DE
